name: RSI Alerts (Discord)

on:
  schedule:
    # run every 10 minutes (Option B1 frequent schedule)
    - cron: "*/10 * * * *"
  workflow_dispatch:

permissions:
  contents: write   # needed to push to alerts-cache branch

concurrency:
  group: rsi-alerts
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Restore alert_cache.json from dedicated branch (alerts-cache) if it exists
      - name: Restore alert cache (from alerts-cache branch)
        run: |
          git fetch origin alerts-cache:alerts-cache || true
          if git rev-parse --verify alerts-cache >/dev/null 2>&1; then
            git show alerts-cache:alert_cache.json > alert_cache.json || true
            echo "Restored alert_cache.json from alerts-cache branch."
          else
            echo "No alerts-cache branch yet. Starting fresh."
          fi

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Quick sanity check of the environment
      - name: Verify environment
        run: |
          python --version
          python - << 'PY'
          import pandas as pd, requests
          print("pandas:", pd.__version__)
          print("requests:", requests.__version__)
          PY

      - name: Run RSI alerts
        env:
          TWELVEDATA_API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}
          COINGECKO_DEMO_API_KEY: ${{ secrets.COINGECKO_DEMO_API_KEY }}
          COINGECKO_PRO_API_KEY: ${{ secrets.COINGECKO_PRO_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python alerts_bot.py

      # Save alert_cache.json to a dedicated branch (NOT to main)
      - name: Persist alert cache (to alerts-cache branch)
        if: always()
        run: |
          if [ -f alert_cache.json ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git checkout -B alerts-cache
            git add alert_cache.json
            git commit -m "chore(cache): update alert cache [skip ci]" || true
            git push origin alerts-cache
            echo "Cache updated on alerts-cache branch."
          else
            echo "No alert_cache.json to persist."
          fi
